# Generated by Django 2.2 on 2020-02-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=350)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='like.Users')),
            ],
        ),
    ]
