# Generated by Django 2.2 on 2020-02-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_materialtypes_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='like.MaterialTypes'),
        ),
    ]
