# Generated by Django 2.2 on 2020-02-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_posts_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-published'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
