# Generated by Django 2.2 on 2020-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0005_auto_20200205_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='uid',
            new_name='login',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
