# Generated by Django 2.2 on 2020-02-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0007_auto_20200206_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='pid',
        ),
        migrations.AddField(
            model_name='comments',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='material_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='variety',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
