# Generated by Django 2.2 on 2020-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0008_auto_20200207_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
