# Generated by Django 2.2 on 2020-02-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0009_auto_20200207_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='like.Posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='like.Users'),
        ),
    ]
